version: '3.8'

x-db-config: &db-config
  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  MYSQL_PORT: ${MYSQL_PORT}

services:
  db:
    image: mariadb
    restart: always
    environment:
      <<: *db-config
    volumes:
      - data:/var/lib/mysql
      - ./config/banco/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-01: &api
    build: 
      context: .
      dockerfile: config/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      HOST: '0.0.0.0'
      MYSQL_HOST: db
      <<: *db-config
    restart: always
    volumes:
      - ./src/:/app/src/

  api-02:
    <<: *api
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      HOST: '0.0.0.0'
      MYSQL_HOST: db
      <<: *db-config

  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:9999"
    depends_on:
      - api-01
      - api-02

volumes:
  data: